[package]
name = "nimiq-tools"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Tools for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[[bin]]
name = "nimiq-bls"
path = "src/bls/main.rs"

[[bin]]
name = "nimiq-address"
path = "src/address/main.rs"

[[bin]]
name = "nimiq-signtx"
path = "src/signtx/main.rs"

[[bin]]
name = "nimiq-rpc-schema"
path = "src/rpc-schema/main.rs"

[[bin]]
name = "nimiq-trim-genesis-config"
path = "src/trim-genesis-config/main.rs"

[[bin]]
name = "nimiq-block-hash"
path = "src/block-hash.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["cargo"] }
convert_case = "0.6"
hex = "0.4"
log = { workspace = true }
quote = "1.0"
rand = "0.8"
schemars = "0.8"
serde = "1.0"
serde_json = "1.0"
syn = { version = "2.0", features = ["full"] }
thiserror = "2.0"
toml = "0.8"

nimiq-block = { workspace = true }
nimiq-bls = { workspace = true }
nimiq-database = { workspace = true }
nimiq-genesis-builder = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-primitives = { workspace = true }
nimiq-serde = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-utils = { workspace = true }
